import type { CuratedOpportunityWatchlist } from "./schema";
import {
  classifySourceCoverageCategories,
  evaluateSourceUniverseCoverage,
  generateSourceCoverageMarkdownReport,
  type SourceUniverseCompletionCriteria,
} from "./sourceCoverage";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

const evaluationCriteria: SourceUniverseCompletionCriteria = {
  min_total_sources: 7,
  min_source_categories: 7,
  min_official_or_semi_official_sources: 5,
  min_official_application_sources: 3,
  min_pattern_or_archive_sources: 1,
  min_high_relevance_sources: 4,
  min_watch_next_cycle_sources: 1,
  max_unclassified_sources: 0,
};

const fixture: CuratedOpportunityWatchlist = {
  applicant_id: "applicant-001",
  generated_for: "Source coverage deterministic evaluation",
  purpose: "Verify Phase 2 source coverage without network or LLM calls.",
  rules: [
    "Coverage measures source-universe completeness; it does not certify eligibility.",
    "Phase 3 discovery remains deferred until curated coverage is complete.",
  ],
  sources: [
    {
      source_id: "fgcu-foundation-fixture",
      name: "FGCU Foundation Fixture",
      url: "https://www.fgcu.edu/example/foundation",
      provider: "Florida Gulf Coast University",
      source_tier: "official",
      source_role: "application_source",
      opportunity_classes: ["foundation scholarship", "undergraduate scholarship"],
      eligibility_signals: ["FGCU undergraduate", "FAFSA", "academic achievement"],
      narrative_signals: ["student persistence"],
      funder_intent_signals: ["donor_identity_alignment"],
      user_001_relevance: "high",
      watch_reason: ["Fixture FGCU internal source"],
      actionability: "watch_next_cycle",
      current_status: "closed",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["FGCU internal fixture"],
    },
    {
      source_id: "florida-osfa-fixture",
      name: "Florida OSFA Fixture",
      url: "https://www.floridastudentfinancialaidsg.org/example",
      provider: "Florida Department of Education OSFA",
      source_tier: "official",
      source_role: "monitoring_source",
      opportunity_classes: ["state aid", "grant"],
      eligibility_signals: ["Florida resident", "FAFSA", "financial need"],
      narrative_signals: ["public education access"],
      funder_intent_signals: ["need_based_mobility"],
      user_001_relevance: "high",
      watch_reason: ["Fixture Florida public aid source"],
      actionability: "needs_verification",
      current_status: "unknown",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Florida public aid fixture"],
    },
    {
      source_id: "rankin-fixture",
      name: "Jeannette Rankin Fixture",
      url: "https://rankinfoundation.org/example",
      provider: "Jeannette Rankin Foundation",
      source_tier: "official",
      source_role: "application_source",
      opportunity_classes: ["scholar grant"],
      eligibility_signals: ["adult learner", "nontraditional student", "first bachelor"],
      narrative_signals: ["returning learner", "education after interruption"],
      funder_intent_signals: ["adult_education_completion"],
      user_001_relevance: "high",
      watch_reason: ["Fixture adult returning learner source"],
      actionability: "needs_verification",
      current_status: "upcoming",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Adult learner fixture"],
    },
    {
      source_id: "patsy-mink-fixture",
      name: "Patsy Mink Fixture",
      url: "https://www.patsyminkfoundation.org/example",
      provider: "Patsy Mink Foundation",
      source_tier: "official",
      source_role: "application_source",
      opportunity_classes: ["education support award"],
      eligibility_signals: ["woman", "mother", "financial need"],
      narrative_signals: ["family responsibility"],
      funder_intent_signals: ["women_advancement"],
      user_001_relevance: "high",
      watch_reason: ["Fixture women mothers caregivers source"],
      actionability: "needs_verification",
      current_status: "open",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Women/mothers fixture"],
    },
    {
      source_id: "paralegal-fixture",
      name: "Paralegal Foundation Fixture",
      url: "https://example.org/paralegal-scholarship",
      provider: "Example Paralegal Association",
      source_tier: "semi_official",
      source_role: "monitoring_source",
      opportunity_classes: ["paralegal scholarship", "law related scholarship"],
      eligibility_signals: ["legal studies", "paralegal", "public service"],
      narrative_signals: ["legal profession access"],
      funder_intent_signals: ["legal_profession_access"],
      user_001_relevance: "medium",
      watch_reason: ["Fixture legal/paralegal source"],
      actionability: "needs_verification",
      current_status: "unknown",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Legal/paralegal fixture"],
    },
    {
      source_id: "swfl-community-fixture",
      name: "Southwest Florida Community Foundation Fixture",
      url: "https://example.org/swfl-community-scholarships",
      provider: "Southwest Florida Community Foundation",
      source_tier: "semi_official",
      source_role: "monitoring_source",
      opportunity_classes: ["local scholarship", "community foundation scholarship"],
      eligibility_signals: ["Lee County", "Fort Myers", "Collier County"],
      narrative_signals: ["community service"],
      funder_intent_signals: ["civic_leadership"],
      user_001_relevance: "medium",
      watch_reason: ["Fixture local Southwest Florida source"],
      actionability: "monitor_only",
      current_status: "unknown",
      verification_policy: "official_source_required",
      enabled: true,
      refresh_interval_hours: 24,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Local SWFL fixture"],
    },
    {
      source_id: "bigfuture-archive-fixture",
      name: "BigFuture Archive Fixture",
      url: "https://bigfuture.collegeboard.org/example",
      provider: "College Board BigFuture",
      source_tier: "aggregator",
      source_role: "pattern_archive",
      opportunity_classes: ["scholarship directory"],
      eligibility_signals: ["directory"],
      narrative_signals: ["pattern learning"],
      funder_intent_signals: ["discovery"],
      user_001_relevance: "pattern_only",
      watch_reason: ["Fixture discovery aggregator archive"],
      actionability: "pattern_only",
      current_status: "pattern_only",
      verification_policy: "pattern_only_no_recommendation",
      enabled: true,
      refresh_interval_hours: 168,
      last_checked_at: null,
      last_success_at: null,
      last_changed_at: null,
      content_hash: null,
      last_observed_signal_summary: null,
      failure_count: 0,
      notes: ["Discovery aggregator archive fixture"],
    },
  ],
};

const report = evaluateSourceUniverseCoverage(
  fixture,
  evaluationCriteria,
  new Date("2026-07-30T00:00:00.000Z")
);

assert(report.completion_completed, "Expected fixture coverage to be complete");
assert(report.source_count === 7, "Expected seven fixture sources");
assert(report.coverage_gaps.length === 0, "Expected no coverage gaps");
assert(
  classifySourceCoverageCategories(fixture.sources[0]).includes("FGCU_INTERNAL"),
  "Expected FGCU fixture classification"
);
assert(
  classifySourceCoverageCategories(fixture.sources[6]).includes(
    "DISCOVERY_AGGREGATOR_ARCHIVE"
  ),
  "Expected discovery/archive fixture classification"
);
assert(
  generateSourceCoverageMarkdownReport(report).includes("Phase 3 Deferral Rule"),
  "Coverage report should preserve Phase 3 deferral"
);

console.log(
  JSON.stringify(
    {
      source_coverage_evaluation: "passed",
      source_count: report.source_count,
      completion_completed: report.completion_completed,
      active_categories: Object.values(report.category_counts).filter((count) => count > 0)
        .length,
    },
    null,
    2
  )
);
